version: '3.7'
services:
  symfony:
    build: .
    container_name: symfony.wiredbeauty
    #    restart: always
    volumes:
      - './:/var/www/html'
    ports:
      - '8080:80'
      - '465:465'
    depends_on:
      - mysql
    entrypoint: /usr/bin/init_project
  mysql:
    build: docker/mysql/.
    container_name: mysql.wiredbeauty
    #    restart: always
    volumes:
      - 'data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=wiredbeauty
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.wiredbeauty
    #    restart: always
    links:
      - mysql:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
volumes:
  data: {}